FROM node:20-alpine

# expose frontend port
EXPOSE 8080

# create necessary work directory
RUN mkdir -p /frontend/public /frontend/src
WORKDIR /frontend 

# copy local files to container
COPY package.json /frontend/package.json
COPY yarn.lock /frontend/yarn.lock
COPY http.js /frontend/http.js
COPY vite.* /frontend


# install packages
RUN yarn install

# Download chromium for Puppeteer browser tests
# RUN npm install playwright
# RUN npx playwright install chrome
CMD ["yarn", "run", "dev"]
