# docker-compose exec <service-name> /bin/bash
# docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' term-project-2024-team-4-postgres-1
version: "3.9"

services:

  mongodb:
    image: mongo:latest
    container_name: point_mongo
    volumes:
      - /Users/FrankyB/fgrams/Projects/databases/pblank:/data/db
    ports:
      - "27017:27017"
    env_file:
      - ./backend/.docker.env

  # set up backend
  backend:
    build:
      context: ./backend
      dockerfile: dev.dockerfile
    volumes:
      - /Users/FrankyB/fgrams/Projects/databases/pblank_uploads:/backend/uploads
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.docker.env
    depends_on:
      - mongodb

  # set up frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend
    ports:
      - "8080:8080"
